[package]
name = "todolist"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
sqlx = "0.8.2"
thiserror = "1.0.64"
tokio = "1.40.0"
warp = "0.3.7"
